### ISSUE TITLE
ImportError: cannot import name matmul

### ISSUE THREAD

**Issue by softwarekitty** [leegao/RegexEnumerator#1]
sorry if this is a noob issue - I'd like to play with your program, but have trouble.  Could there be another dependency besides the three you listed?

~/h/d/p/RegexEnumerator ❯❯❯ pip freeze | grep -E '(scipy|sympy|numpy)'
numpy==1.11.2
scipy==0.18.1
sympy==1.0
~/h/d/p/RegexEnumerator ❯❯❯ python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 12:54:16)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import scipy
>>> import sympy
>>> from regex_enumerate import enumerate_coefficients
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "regex_enumerate/__init__.py", line 1, in <module>
    from .enumerate import enumerate_coefficients, exact_coefficients, exact, \
  File "regex_enumerate/enumerate.py", line 5, in <module>
    from numpy import array, zeros, eye, matmul
ImportError: cannot import name matmul
>>> exit()

**Comment by leegao** [comment]
Huh that's really strange. I have the same version of numpy as you too, which makes this even more strange. According to the docs, this method should be implemented by version 1.10. Nevertheless, since all of the matrices I'm dealing with range over numerical fields, I think `np.dot` (which definitely should be available) should suffice here.

**Comment by leegao** [comment]
https://github.com/leegao/RegexEnumerator/commit/0a914236015493404b748024792b1bc16d308bfc ought to fix this, let me know if this works from your end :)

**Comment by softwarekitty** [comment]
works now!

having issues for regexes without * or +, for example:

>>> print(enumerate_coefficients('0|1|2'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "regex_enumerate/enumerate.py", line 187, in enumerate_coefficients
    formula = algebraic_form(regex, what, threshold)
  File "regex_enumerate/enumerate.py", line 209, in algebraic_form
    extract_coefficients_algebraically(regex, what, threshold)
  File "regex_enumerate/enumerate.py", line 176, in extract_coefficients_algebraically
    partial_coefficients = solve(vandermonde_matrix, target)
  File "/Library/Python/2.7/site-packages/numpy/linalg/linalg.py", line 357, in solve
    _assertRankAtLeast2(a)
  File "/Library/Python/2.7/site-packages/numpy/linalg/linalg.py", line 202, in _assertRankAtLeast2
    'at least two-dimensional' % len(a.shape))
numpy.linalg.linalg.LinAlgError: 1-dimensional array given. Array must be at least two-dimensional
>>> print(enumerate_coefficients('0*'))
<generator object <genexpr> at 0x10822c550>

is the regex '0|1|2' invalid somehow?

**Comment by leegao** [comment]
Unfortunately, one of the limitations right now is if your grammar doesn't have a loop in there somewhere :P 

The reason being (for now, I plan on fixing this up) is that the approach is based on factoring the rational function p/q. However, when p/q = 0, this fails spectacularly. I'll see if I can't fix this from my end. Thanks for reporting! :)

**Comment by leegao** [comment]
https://github.com/leegao/RegexEnumerator/commit/7c944d690cea62b490dd643d25438c76f570b88d should do the trick
